---
title: "LabelTibble"
output: pdf_document
date: "2026-01-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(xml2)
```

Bringing in the xml file with all record labels info and converting it to a tidy tibble
Shout out https://r4ds.hadley.nz/rectangling.html
and https://xml2.r-lib.org/index.html
```{r}
#read in xml file
labelsxml <- read_xml("/Users/jakehinz/Documents/GitHub/Discogs_Data_Analysis/discogs_20260101_labels.xml")

#convert to list then tibble
labels_tidy_tibble <- labelsxml |> as_list() |> as_tibble() |> unnest_wider(labels) |>
  select(id, name, profile, parentLabel, contactinfo, data_quality) |>
  unnest_wider(id, names_sep = "_") |> unnest_wider(name, names_sep = "_") |> unnest_wider(contactinfo, names_sep = "_") |>
  unnest_wider(profile, names_sep = "_") |> unnest_wider(data_quality, names_sep = "_") |>
  unnest_wider(parentLabel, names_sep = "_")
```

Creating smaller dataset to test ideas on
```{r}
set.seed(152)
test_set <- labels_tidy_tibble %>% sample_n(25000)
```

Fixing column names, converting types
```{r}
#column names
labels_tidy_tibble <- labels_tidy_tibble |> rename("id" = "id_1", "name" = "name_1", "profile" = "profile_1", "parentLabel" = "parentLabel_1", "contactInfo" = "contactinfo_1", "dataQuality" = "data_quality_1")

#types
labels_tidy_tibble$dataQuality <- as_factor(labels_tidy_tibble$dataQuality)
labels_tidy_tibble <- labels_tidy_tibble %>% mutate(id = as.numeric(id))
```

Exploratory data analysis
```{r, fig.width=10, fig.height=4}
#dataQuality counts
ggplot(data = labels_tidy_tibble, mapping = aes(x = dataQuality)) +
  geom_bar()

#subLabel counts
labels_tidy_tibble <- labels_tidy_tibble %>% mutate(subLabel = ifelse(is.na(parentLabel) == TRUE, 0, 1))
ggplot(data = labels_tidy_tibble, mapping = aes(x = subLabel)) +
  geom_bar()

#log(profileLength) ~ dataQuality
labels_tidy_tibble <- labels_tidy_tibble %>% mutate(profileLength = str_length(profile))
labels_tidy_tibble <- labels_tidy_tibble %>% mutate(profileLength = ifelse(is.na(profile), 1, profileLength))
ggplot(data = labels_tidy_tibble, mapping = aes(x = dataQuality, y = log(profileLength+1))) +
  geom_boxplot()

#longest profile length
labels_tidy_tibble %>% filter(profileLength == 23183)

#Predicting subLabel by profileLength
labels_tidy_tibble %>% ggplot(mapping = aes(x = log(profileLength), y = ifelse(subLabel==1, TRUE, FALSE))) +
  geom_boxplot()

labels_tidy_tibble <- labels_tidy_tibble %>% mutate(logProfileLength = log(profileLength))

model1 <- glm(subLabel ~ logProfileLength, family=binomial, data=labels_tidy_tibble)
summary(model1)

ggplot(test_set, mapping = aes(x = logProfileLength, y = subLabel)) + geom_jitter(width = 0.3, height = 0.4) +
      stat_smooth(method="glm", color="green", se=FALSE, method.args = list(family=binomial))
```










Getting a snippet of masters release data to look at data structure
```{zsh}
head -n 3000 /Users/jakehinz/Documents/GitHub/Discogs_Data_Analysis/discogs_20260101_masters.xml
brew install libxml2
```
```{zsh}
xmllint --format /Users/jakehinz/Documents/GitHub/Discogs_Data_Analysis/snippet.xml
```



Iterating over xml
Shout out https://www.trivialproblems.com/posts/incremental-xml-parsing-with-python/
https://stackoverflow.com/questions/12792998/elementtree-iterparse-strategy
```{python}
import xml.etree.ElementTree as ET

iter = ET.iterparse("/Users/jakehinz/Documents/GitHub/Discogs_Data_Analysis/discogs_20260101_masters.xml", events=["start", "end"])
x = 0
path = []
# allArtists = []
for event, elem in iter:
  text = elem.text
  tag = elem.tag
  #creating path list
  if event == 'start':
    path.append(tag)
  elif event == 'end':
    path.pop()

  if 'videos' in path:
    continue
        
  print(event)
  print(text)
  print(tag)
  
  if tag == "main_release" and event == "start":
    releaseID = text
    
  # if "artists" in path:
  #  if tag == 'id' and event == 'start':
  #    currentArtist = []
  #    currentArtist.append(elem.text)
  #  if tag == 'name' and event == 'start':
  #    currentArtist.append(elem.text)
  #    allArtists.append(currentArtist)
  
  print()
  print(releaseID)
  print()
  x = x+1
  if x==200:
    break
```







